### ISSUE TITLE
Production studies missing GPS & accelerometer data

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-android#10]
Maria has observed missing GPS and accelerometer data on Androids and iPhones (both of various versions) in production research studies.

> *"Also, the missingness of GPS/accelerometer data seems to be for both Android & iPhones. Almost everyone has some amount of missing data, but some have most of the data (20% missing is our best subject iPhone 7 iOS 10.2) and some have barely any data (83% missing is our worst subject iPhone 6s+ iOS 10.2). I don't see a consistent pattern between phone type and degree of missingness (at first, I thought the iPhone 6 family were bad and iPhone 5/7 were fine, but the more I looked, I realized there were good 6's and bad 5's or 7's (although less frequently))."*
> (From Maria's email on Friday, 2/17/17, subject line "Fwd: Beiwe Bug")

**Comment by sesterki** [comment]
It is unclear what caused this issue originally. We fixed various related bugs, but this could also be related to #27. Closing this issue to remove duplicates.
