### ISSUE TITLE
Survey notifications reappear for completed surveys on app close

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-android#14]
@mariasimoneau says:
>tester [Kenzie?] noticed that the surveys are repeated when she actually closes the app. For example, if she completes the survey(s) and then closes out of the app to 'save battery,' she will get a notification to complete the same surveys. This will keep happening as long as she closes out of the app. If she doesn't close out of the app, then she does not get the repeated notifications.

I split this off from [beiwe-backend Issue 6](https://github.com/onnela-lab/beiwe-backend/issues/6).

**Comment by biblicabeebli** [comment]
This issue is substantially out of date and also underlying behavior and notification serving via push notifications from the backend have changed, closing this issue. (also it is ancient.)
