### ISSUE TITLE
Can't install Beiwe on Android Moto phone

### ISSUE THREAD

**Issue by mariasimoneau** [onnela-lab/beiwe-android#16]
5/31/17 10 am then 4pm installs.  Collaborator reported: I had a participant today who has an android phone, Moto G 2nd Generation, Android Version 6.0. We were able to download Beiwe and fill out the ID, password, researcher phone #, etc., but once she tried to submit that form, it would crash. We un-installed it, re-installed it, and the same thing happened. We also tried it on 2 different wifi networks. I wanted to let you know and find out if there’s a solution to this issue, in case it happens in the future.   they rebooted the phone in between installs.    I'm listing this here to keep track of it but it's a low priority since we don't have much to go on.

**Comment by zagorsky** [comment]
We don't have enough information to debug this, especially since we got this error report before we added Sentry to the Android app.  Now that the Android app has Sentry in it, we should receive stack traces from crashes that happened before registration completed.
