### ISSUE TITLE
Unable to destroy activity: AudioRecorderActivity

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-android#22]
May be an error in the background encryption process when a user finishes an audio recording: https://sentry.io/onnela-lab/production/issues/460388785/
https://sentry.io/onnela-lab/production/issues/473193501/
https://sentry.io/onnela-lab/production/issues/531211907/
https://sentry.io/onnela-lab/android-development/issues/541896866/

**To reproduce this bug**, open an Audio survey, press the Play button, wait a few seconds, and then kill the app from the task switcher.

**Comment by sesterki** [comment]
Fixed in commit 34618e582e9006ccdecc6cf6598cf2920602dccc

**Comment by sesterki** [comment]
Removed the function in c14aa565ba75ce727df54fe19f578a9c4450a306

**Comment by zagorsky** [comment]
Should be fixed in 34618e5, app version 2.3.3 and above.
