### ISSUE TITLE
Beiwe app hangs on a white screen on Google Pixel phone

### ISSUE THREAD

**Issue by mariasimoneau** [onnela-lab/beiwe-android#25]
The Beiwe app hangs on a white screen after the app is installed and during the registration process after permission is given to access SMS messages. This happens with both apps -- the original Beiwe from studies.beiwe.org/download or Beiwe2 on the app store.  Phone is a Google pixel on android version 8.1.0.

Second report - I had a participant today that downloaded Beiwe on their Pixel phone and whenever they opened the app after installing it just gave them a blank page.

**Comment by zagorsky** [comment]
We found and fixed the issue.

Android 8.0 and above no longer allows apps to read the Bluetooth MAC Address, as Google announced in [this blog post](https://android-developers.googleblog.com/2017/04/changes-to-device-identifiers-in.html).  We added code in [commit 3fcf089](https://github.com/onnela-lab/beiwe-android/commit/3fcf089b66e838acea76d7d727ff79f078e40098) to write a blank Bluetooth MAC Address when the app isn't able to read it.

We pushed a new version of the app (24, aka 2.2.5) to the Google Play Store Private Beta (not yet rolled out to the public), and an Onnela Lab Server edition for download here: https://s3.amazonaws.com/beiwe-app-backups/release/Beiwe-2.2.5-onnelaLabServer-release.apk (this does *not* affect the version available for download at studies.beiwe.org/download).
