### ISSUE TITLE
In registration, doesn't have permission READ_PHONE_STATE or READ_SMS

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-android#29]
https://sentry.io/onnela-lab/android-release/issues/553214852/

This is the first stack trace we got in the Android Release Sentry project, which means it came from version 2.3.2 of the app, which I only released on Monday, May 7.

**Comment by sesterki** [comment]
I took a look at this issue and fixed it in commit 9b7b46e2eab16f435e525ee37ab259db428a163d

**Comment by zagorsky** [comment]
Sean fixed this in commit 9b7b46e.  We will compile and distribute a new app version soon- this should be fixed in 2.3.3 and above.
