### ISSUE TITLE
Update compileSdkVersion to at least 26

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-android#37]
By November 2018, Google Play will force us to update the target SDK version to at least 26 (Android 8.0):

> "Your app currently targets API level 23 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance.  From August 2018, new apps must target at least Android 8.0 (API level 26).  From November 2018, app updates must target Android 8.0 (API level 26)."

Updating the target SDK to 26 involves some serious changes.  We'll need to make changes to at least these areas:

* How the BackgroundService runs: https://developer.android.com/about/versions/oreo/background.  However, does Beiwe's BackgroundService count as a "[Bound Service](https://developer.android.com/guide/components/bound-services)"?  The Android 8 update notes say *"These rules do not affect bound services in any way."* 

* How the app registers to receive Intents.  These may be the only Intents we can still register to receive in the Manifest: https://developer.android.com/guide/components/broadcast-exceptions

* How the app receives location updates: https://developer.android.com/about/versions/oreo/background-location-limits

Can you please update the app to target at least version 26, and:

1. Figure out what's going to break, and fix it

2. Decide if we should skip past version 26, and target anything higher

**Comment by sesterki** [comment]
I created a branch to start looking into this. The branch is called api_target_26 and the current commit is ac59c4a47624d26ef57aa096f1fffcff1e7c0ca1

**Comment by zagorsky** [comment]
@sesterki handled in 370f4ac, app version *greater than* 2.3.3.  I ran this for 5 days on an Android 7.0 phone and saw no impact: it still produced App Log and Accelerometer files every hour.
