### ISSUE TITLE
Data upload via cellular network

### ISSUE THREAD

**Issue by benazir0** [onnela-lab/beiwe-android#44]
One of our users reported that over 10 GB of data was uploaded over the mobile network in 10 days. It's worth looking into this matter whether actually it is the case.

We built the apk from the master branch with the latest commit. We haven't modified any device settings on the app. Here is the app settings on the beiwe server:
![image](https://user-images.githubusercontent.com/39503792/45299713-c65fa180-b54f-11e8-9d48-af5b13336230.png)

**Comment by biblicabeebli** [comment]
Critical Details:
The value for Allow Data Upload Over Cellular defaults to False on study creation.
Values for all of a study's device settings are only pushed once, at registration.

Please try and determine whether you had the upload over cellular feature enabled when the user signed up for the study.  If the user uninstalls Beiwe, reinstalls, and re-signs up for your study and no longer encounters cellular data usage then it is the case that this setting was enabled when the user signed up.

If possible please provide the version of Android the device was running.
If you are able to replicate the issue it would be very helpful if you can provide steps to reproduce it.

**Comment by biblicabeebli** [comment]
This is the only report of this behavior, and user provided no additional information. closing.
