### ISSUE TITLE
Missing Android Accelerometer Data

### ISSUE THREAD

**Issue by jadraketx** [onnela-lab/beiwe-android#58]
Hello - we have been using Beiwe App version 2.5.0, build 37 in a production study. We noticed that accelerometer data files are being created but only contain the header. The log files show Accelerometer ON and OFF events but no data are populating the files corresponding to those times. We're trying to debug the issue but looking for some guidance. Could these be issues with permissions or phone settings? Testing this issue with a group member, we were able to recreate the issue and confirmed that Beiwe wasn't listed under apps with battery optimization on. Accelerometer data is generated immediately following registration but doesn't last long. Alternatively, could this be an issue with this version of Beiwe and we should deploy the most up-to-date version? I noticed there were some missing data issues for versions slightly older than the one we are using. 

Appreciate any advice you may have. Thanks!

Justin

**Comment by zagorsky** [comment]
@jadraketx lucky timing for you: we just created a fix for that!

In Android OS versions 9 and above, the accelerometer and gyroscope are blocked from receiving data when the app is in the background.  We just made a change to the Beiwe Android app to move the data listeners (including accel and gyro) into a Foreground Service.  That's available starting in v3.1.0 of the Beiwe app, which is in Open Beta on the Google Play Store as of this morning.

**Comment by jadraketx** [comment]
@zagorsky that is extremely lucky for me! Certainly appreciate the updates and fixes yall put out. So it sounds like Android's decision forcing these data listeners to be Foreground Services will likely have a big impact on sampling consistency?

**Comment by zagorsky** [comment]
Yep, correct.
