### ISSUE TITLE
Repetitive/persistent Android notifications after survey completion

### ISSUE THREAD

**Issue by hydawo** [onnela-lab/beiwe-android#64]
@biblicabeebli an Android user (**tzgxnl2y**) in the "[MGH Berry Feasibility and Sensitivity of a SMART for Amyotrophic Lateral Sclerosis 3.0](https://studies.beiwe.org/view_study/899)" study reported receiving repetitive/persistent notifications even after completing a survey. Their data streams look good and nothing out of the ordinary for survey answers/timings streams. Here is what the user reported to the study team:

> I get reminders to do the surveys.   I click the reminder and it brings me to the app and the survey.  I hit submit when completed, and before that reminder would go away.  Now it just reappears with the present time .
> 
> For example.  I get the reminder at 10am.   If I do the survey at 11am, I get a reminder for the time I did the survey.  And all the reminders at that moment get updated to the present time.  And it just keeps flipping as it updates the time. It updates every minute, so my inbox is flipping non-stop.   It is wild.  It really is interfering with my phone.
> 
> I can’t even catch a picture as it flips so quickly so I had my brother take a picture of it.   You can see the time is 9:04 pm on all of them.   That will change every minute.
> 
> I have done multiple surveys, but they all reappear.   Nothing goes away.
> 
> ![Participant's Beiwe Notifications](https://user-images.githubusercontent.com/21285757/226642850-15aef5c0-f5ed-4152-98dd-3746a2ea6901.jpg)

I asked the study coordinator to have the user perform a full uninstall, restart, and re-registration with "Easy Enrollment" enabled. Based on their activity times, it looks like they completed this late last Friday (3/17/23):

<img width="1064" alt="Google Chrome at 10 51 14 on 2023-03-21@2x" src="https://user-images.githubusercontent.com/21285757/226644685-7b7bac26-826f-49f0-aa46-aae8f1ca731f.png">

I'll follow up with the study team to find out whether this resolved the issue.

**Comment by joannakennedyharvard** [comment]
Users "42t6jgb4" and "z8tcvqyk" in the "[NHS3/GUTS Beiwe Smartphone Study_1](https://nhs.beiwe.org/view_study/4)" study reported a similar issue without a screenshot.

I advised their team to do the same as above (full uninstall, restart phone, un-register device, reinstall, re-register using same ID).

**Comment by biblicabeebli** [comment]
I've skimmed this issue, thanks for the details, I will try to look into it, I'm just currently in iOS land.

Candidate sources are bugs in the survey scheduling logic, the notification management logic, or in persistence behavior causing background service restarts. My guess is notifications, and its probably not a push notifications bug.

**Comment by joannakennedyharvard** [comment]
Also, user "a95c8qzw" from the same "[NHS3/GUTS Beiwe Smartphone Study_1](https://nhs.beiwe.org/view_study/4)" study.

This user uninstalled and reinstalled  (full uninstall, restart phone, un-register device, reinstall, re-register using same ID). The study team says this seemed to solve the problem for this participant.

**Comment by biblicabeebli** [comment]
Thaaaaat's weird, indicates some sort of cumulative glitch.

**Comment by hydawo** [comment]
Only the NHS3/GUTS study has let us know that a reinstallation/reregistration resolved the issue. I have not heard back from the other teams yet. We did ask the NHS3/GUTS team to let us know if this issue recurs for the same user (a95c8qzw) or if it starts happening for other users.

**Comment by joannakennedyharvard** [comment]
User "kjhi74g5" from the [MGH Berry Feasibility and Sensitivity of a SMART for Amyotrophic Lateral Sclerosis 2.0](MGH Berry Feasibility and Sensitivity of a SMART for Amyotrophic Lateral Sclerosis 2.0) with a similar issue without a screenshot.

I advised their team to do the same as above (full uninstall, restart phone, un-register device, reinstall, re-register using same ID) and asked about if those steps solved the issue for their user "tzgxnl2y" that provided the screenshots above.

**Comment by hydawo** [comment]
> @biblicabeebli an Android user (**tzgxnl2y**) in the "[MGH Berry Feasibility and Sensitivity of a SMART for Amyotrophic Lateral Sclerosis 3.0](https://studies.beiwe.org/view_study/899)" study reported receiving repetitive/persistent notifications even after completing a survey. Their data streams look good and nothing out of the ordinary for survey answers/timings streams. Here is what the user reported to the study team:
> 
> > I get reminders to do the surveys.   I click the reminder and it brings me to the app and the survey.  I hit submit when completed, and before that reminder would go away.  Now it just reappears with the present time .
> > For example.  I get the reminder at 10am.   If I do the survey at 11am, I get a reminder for the time I did the survey.  And all the reminders at that moment get updated to the present time.  And it just keeps flipping as it updates the time. It updates every minute, so my inbox is flipping non-stop.   It is wild.  It really is interfering with my phone.
> > I can’t even catch a picture as it flips so quickly so I had my brother take a picture of it.   You can see the time is 9:04 pm on all of them.   That will change every minute.
> > I have done multiple surveys, but they all reappear.   Nothing goes away.
> > ![Participant's Beiwe Notifications](https://user-images.githubusercontent.com/21285757/226642850-15aef5c0-f5ed-4152-98dd-3746a2ea6901.jpg)
> 
> I asked the study coordinator to have the user perform a full uninstall, restart, and re-registration with "Easy Enrollment" enabled. Based on their activity times, it looks like they completed this late last Friday (3/17/23):
> 
> <img alt="Google Chrome at 10 51 14 on 2023-03-21@2x" width="1064" src="https://user-images.githubusercontent.com/21285757/226644685-7b7bac26-826f-49f0-aa46-aae8f1ca731f.png">
> 
> I'll follow up with the study team to find out whether this resolved the issue.

This same user is reporting this issue again (after reinstallation/reregistration fixed the issue for a short period of time). @biblicabeebli can we please look into this ASAP?

Thank you!

**Comment by hydawo** [comment]
@biblicabeebli moving this to current sprint

**Comment by biblicabeebli** [comment]
Working on it!

**Comment by biblicabeebli** [comment]
After more review I noticed that first user's study has 10-second intervals for the accelerometer data stream - the way version 3.4.x of the android app works is that it runs ALL the app-state logic whenever ANY timer event triggers.  My guess is that this issue is only being encountered by participants in studies with these very frequent events, or at least it isn't noticed by other people.  (We will never get a report of every weird ui glitch or bug.)

The only detail I don't understand is why the survey notification _is not getting dismissed_ for some participants.  I've checked the code - there are no special identifiers, everything is premised on the survey id and there can only be one survey notification per survey id, and the dismissNotification function works as expected.  I think this is just user error due to the notifications not stating which survey they point to.

**Comment by biblicabeebli** [comment]
I have now been able to replicate the scenario the user is seeing.  I think the animation of shifting notification sliding around is skipped if there are only 2 or 3, or if the device is slow.  My fix  fixes it.

I think its ok to push the fix out immediately.

**Comment by biblicabeebli** [comment]
yeah, I've sat on it for a day, this is safe, I'm pushing it.

**Comment by biblicabeebli** [comment]
App version 3.4.2 is live on the link on the bottom of beiwe website pages, in-process for the app store.

**Comment by biblicabeebli** [comment]
@hydawo you can update people that there is a probable fix out / out-soon.

**Comment by hydawo** [comment]
@biblicabeebli great thanks Eli, we will start having studies install the new Android version and report back on any further issues. We will keep this open for now...
