### ISSUE TITLE
Android 8 Registration Bug - App Version 3.5.4

### ISSUE THREAD

**Issue by hydawo** [onnela-lab/beiwe-android#73]
At least one Android 8 user has reported the app crashing upon clicking the registration button in app version 3.4.5

**Comment by biblicabeebli** [comment]
Unknown what the exact range of versions it affects, based on changes to permissions - the most likely source - it would probably affect Android 9 too, but not 10.

**Comment by hydawo** [comment]
Update: Two other study teams have reported issues with Android users registering using 3.5.4.

**Comment by biblicabeebli** [comment]
3.5.6 up on my google drive https://drive.google.com/drive/folders/1g0zQmwtvhVYIr2QBa5qSexUuvL4kiU1a for testing, I'm going to push this out to the download link.

@hydawo still waiting on go ahead to remove Play store version.

**Comment by hydawo** [comment]
I was able to register and take surveys with branching logic without issue on my test phone, but I'm waiting to hear feedback from testers with older Android versions. I'll keep you updated, but we will likely push 3.5.6 live tomorrow (10/5/23). Thank you!

**Comment by biblicabeebli** [comment]
this issue is confirmed resolved, download and install 3.5.6.  Source of bug was an undocumented change in the Android PowerManager class somewhere between Android 8 and 13.
