### ISSUE TITLE
Android Phone registration displays incorrect directions if permission is not assigned.

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-android#77]
This is the issue where the app repeatedly bumps the participant back to the app settings if they disallowed the "SMS" permissions.

This is very dumb - sms and phone permissions used to be differently unified or something?

TLDR: in like 2016 I had to make a decision to grab one of the SMS or Phone permissions, either of which allows access to the phone number. I chose SMS because the related/unified phone number access permissions are slightly less invasive. But now it wants you to go and check the Phone permissions. I'm changing it to Phone permissions in the code, and in the message that is prompted.

There will be a 3.6.7 pushed shortly.

**Comment by biblicabeebli** [comment]
lmao the chinese directions are .... well:
> In order to register for the research project, Beiwe needs to be connected to the communication function of your device. If you see a link request between Beiwe and the communication function of the device, please click "Allow". However, according to the research picture book, you can cancel the link to this function after completing the software registration.

@hydawo @clementzach can I get some eyeballs on the translations here? (and do we have anyone that speaks and reads chinese?)

the two string keys in the xml files are `permission_registration_read_sms_alert` and `permission_registration_actually_need_sms_alert (I'll change their names later if I really care.)

**Comment by biblicabeebli** [comment]
Older devices - because the permissions check bifurcated in Android 11 because of course it did.

I have been able to test this on my Android 8 tablet - admittedly it doesn't have a phone number, but it looks like the logic checks and .... it doesn't explode when the telephony stuff is accessed with a permissions error, so I think this is functional with androids before 11.

**Comment by biblicabeebli** [comment]
It's pushed to servers.
Actually servers are now at 3.5.8, that's a developer update its not important to tell anyone.
and my google drive is currently empty.
closing.

**Comment by biblicabeebli** [comment]
Reopemning based on @hydawo report, original message was:
...ran into hard stops for phone call and location access. Can’t register without allowing both of those. I wasn’t prompted for sms/call log permission though.

Providing the necessary permissions for the study data streams has always been a hard stop.

Location permissions on android 11+ now requires you go into settings and select All The Time.

What's the bug? (desired change?)

I can probably make phone (formerly sms) permissions optional during registration ~relatively easily. It might have weird side effects at like forest time because there may be expectations about the presence of a value in the identifiers.

I cannot make the real data streams optional easily/quickly. It's a potentially Huge amount of work and testing. It's  just one of those things that I can't account for before starting, it's an old constant fact that participants would be required to grant all permissions for a study. I would rate building that as a poor use of my time.

**Comment by hydawo** [comment]
@biblicabeebli I am Running Android v3.5.9 (official release) on Android 13

1. Before registration, I am prompted for **Phone Call Management** and **Location** permissions as hard-stops. Can we please remove the hard-stop Phone Call Management permissions (not the permission overall which would affect all studies)? I believe this will affect the identifiers stream, but we can make this clear to study teams and let them decide if they want to allow users to opt out of the Phone Call Management permission
2. Post-registration I am prompted for notifications/SMS/call text/and another phone permission -- **are users now only prompted for these permissions if they're study is collecting them?**

**Comment by biblicabeebli** [comment]
> Post-registration I am prompted for notifications/SMS/call text/and another phone permission -- are users now only prompted for these permissions if they're study is collecting them?
Yes.

**Comment by biblicabeebli** [comment]
I have been working on a new build, currently  I have the phone call management or whatever prompt down to prompting once.

**Comment by biblicabeebli** [comment]
There's a beta build on https://drive.google.com/drive/folders/1g0zQmwtvhVYIr2QBa5qSexUuvL4kiU1a?usp=sharing

Have not tested android 8 yet, but not expecting incompatablitiy.

Todo: test ios registration on empty consent form.

**Comment by hydawo** [comment]
@biblicabeebli I tested v3.5.10 and registered to study "[HPHCI_Oken_Project Viva_Beiwe](HPHCI_Oken_Project Viva_Beiwe)" on our Studies server. This study is collecting GPS data, but it is NOT collecting any commstats data. I have screenshots of every prompt (whether through Beiwe or Android) if needed.

I received the following prompts:

**Prior to registration**

1. "Manage Phone Calls" (Beiwe prompt) - note the word registration is misspelled as regisstration
2. "Manage Phone Calls" (Android prompt)

**After Registration**

1. Consent form - I believe this should not be presented if the consent text field is left blank in the study configuration page; however, the web dashboard does not allow you to save a blank consent text field. It returns this message _"Consent Form Text **wos** NOT updated, 'This field cannot be blank.'"_ → I have added this to the [Android consent screen issue #210](https://github.com/onnela-lab/beiwe-discussions/issues/210)
2. "Location Services" (Beiwe prompt)
3. "Location Services" (Android prompt)
4. "Location Services" bump out to Android settings page (Beiwe prompt)
5. "Phone Service" - **this should not have presented given this study is not collecting commstats data** - note that I did not receive an Android prompt (only the Beiwe message about the permission prompt), so we are half way there
6. "Allow run in background" (Beiwe prompt)
7. "Stop optimizing battery usage" (Android prompt)

After installation I tested disabling both 1) Location Services and 2) Phone permission (not sure if this is the call management permission prior to registration or Phone Services permission post-registration)

**Takeaways:**

1. Seems like the app is NOT prompting for data streams that are not being collected, **except** for "Phone Service" Beiwe prompt post-registration (there is not Android prompt for Phone Service"
2. Can you help me understand the difference between the phone prompts before and after registration? Is the first one needed to hash the participants phone number when gathering identifiers and is the second one for phone call log access?

**Comment by biblicabeebli** [comment]
"Phone" is one checkbox in the app's permission settings, but it includes several items.  This is annoying but unavoidable.

**Comment by biblicabeebli** [comment]
Beta 2 with the above fixes in the google drive.
https://drive.google.com/drive/folders/1g0zQmwtvhVYIr2QBa5qSexUuvL4kiU1a?usp=sharing

Also fixes typo of the two Ss that was mentioned.
I have tested the minor variances on Android 8, it works as desired (and as understood, by me, which is important!).

**Comment by biblicabeebli** [comment]
3.5.10 was pushed out at roughly 5pm yesterday.

Would like to close issue as I believe we are synced on this.
