### ISSUE TITLE
Make Android Consent Screen Optional or Turn Off

### ISSUE THREAD

**Issue by hydawo** [onnela-lab/beiwe-android#80]

**Comment by biblicabeebli** [comment]
Errata: old versions of the Android app will crash on this. need to test iOS to see if it crashes. if not this implementation is not viable.

**Comment by hydawo** [comment]
@biblicabeebli I'm closing this issue. I didn't realize I duplicated this issue yesterday. 

https://github.com/onnela-lab/beiwe-discussions/issues/210 has better notes. I will add your comment about 3.5.10 and provide feedback. Thank you!
