### ISSUE TITLE
Fulford corrupted audio files - active study

### ISSUE THREAD

**Issue by joannakennedyharvard** [onnela-lab/beiwe-android#81]
It's broad based an affecting multiple users in an active study. The three participants that have consistent, non-corrupted data before the introduction of MetricWire were enrolled in the study from:
      6skv5ddm 7/11/2022 – 7/25/2022
      9kpvo7zj 7/15/2022 – 8/1/2022
      9a23vpt7 8/19/2023 – 9/13/2022

Here is the information of the subjects that have corrupted samples:

![Image](https://user-images.githubusercontent.com/112563754/277745777-0de300dd-67cc-4cb8-a04e-d34d692878f9.png)

**Comment by biblicabeebli** [comment]
We absolutely do not support running both the MetricWire audio collection alongside the Beiwe Android app ambient audio stream. It is a technical impossibility as far as I am aware.

The first thing to do though is to check if these files are corrupted but still playable with recovery, or are they corrupted data.

Check to see if they are all zeros - try compressing them in a zip file, if it compresses unrealistically (mp4 already has some zlib-style compression built into it so it won't compress well) then there is no data.  After that.... try loading the mp4 file is VLC player and Audacity audio editor, see what they think.

Last test would be using a command line tool like ffmpeg or  mediainfo to look at the file.
